config/routes.rb
Rails.application.routes.draw do
  devise_for :credentials
  #devise_for :users, controllers: { sessions: 'devise/sessions' }
  #devise_for :users, controllers: { sessions: "users/sessions" }
  resources :klasses
  resources :schools
  resources :users#, :only => [:show]
  resources :pages


  root 			to: 'pages#main'

  #match '/schools/add_klass/:id' => 'schools#add_klass', via: :get, as: :add_klass

  #resources :schools do
  #  post :add_klass, :on => :member
  #end

  #unauthenticated do
  #  root :to => 'sessions#new'
  #end

  #authenticated do
  #  root :to => 'pages#main'
  #end
  #get			  'sessions/new'

  #get	 'login'	=> 'sessions#new'
  #post	 'login'	=> 'sessions#create'
  #delete 'logout'	=> 'sessions#destroy'

  #devise_scope :user do
    #get   'login' =>  'devise/sessions#new'
    #get   'logout'=>  'devise/sessions#destroy'
  #  unauthenticated do
    #  root :to => 'sessions#new'
  #  end

    #authenticated do
    #  root :to => 'pages#main'
    #end
  #end
end

app/models/user.rb
class User < ActiveRecord::Base
  ################
  # ASSOCIATIONS #
  ################
  has_one  :credential, dependent: :destroy
  has_many :registrations
  has_many :schools, through: :registrations, source: :registerable, source_type: 'School'
  has_many :klasses, through: :registrations, source: :registerable, source_type: 'Klass'

  ###############
  # VALIDATIONS #
  ###############
  validates_presence_of :credential

  ###########
  # METHODS #
  ###########

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only: [:show, :edit]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  protected

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
  public
    # Returns TRUE is this User is the same as the User trying
    # to access the page.
    #def correct_user?(user)
    #  user == current_user
    #end

    def to_s
      @user.first_name
    end

    def name
      @user.first_name + ' ' + @user.last_name
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label "E-Mail Address" %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label "Role" %><br>
    <%= f.select(:role_ids, options_for_select( Role.order(:title).all.map do |r| 
                                                  ["#{r.title}", r.id] 
                                                end), include_blank: true)%>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "Confirm Password" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label "Address" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.telephone_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label "Address" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.telephone_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% if correct_user?(user) %>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label "E-Mail Address" %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "Confirm Password" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label "Address" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.telephone_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @user.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.credential.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Schools:</strong>
  <ul>
    <%= @user.schools.each do |school| %>
      <li><%= link_to school.name, school %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Classes:</strong>
  <ul>
    <%= @user.klasses.each do |klass| %>
    <li><%= link_to klass.name, klass %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Change Email/Password', edit_credential_registration_path(current_credential) %> |
<%= link_to 'Back', current_user %>