config/routes.rb
Rails.application.routes.draw do
  devise_for :credentials
  #devise_for :users, controllers: { sessions: 'devise/sessions' }
  #devise_for :users, controllers: { sessions: "users/sessions" }
  resources :klasses
  resources :schools
  resources :users#, :only => [:show]
  resources :pages


  root 			to: 'pages#main'

  #match '/schools/add_klass/:id' => 'schools#add_klass', via: :get, as: :add_klass

  #resources :schools do
  #  post :add_klass, :on => :member
  #end

  #unauthenticated do
  #  root :to => 'sessions#new'
  #end

  #authenticated do
  #  root :to => 'pages#main'
  #end
  #get			  'sessions/new'

  #get	 'login'	=> 'sessions#new'
  #post	 'login'	=> 'sessions#create'
  #delete 'logout'	=> 'sessions#destroy'

  #devise_scope :user do
    #get   'login' =>  'devise/sessions#new'
    #get   'logout'=>  'devise/sessions#destroy'
  #  unauthenticated do
    #  root :to => 'sessions#new'
  #  end

    #authenticated do
    #  root :to => 'pages#main'
    #end
  #end
end

app/models/school.rb
class School < ActiveRecord::Base
  include Registerable

  ################
  # ASSOCIATIONS #
  ################
  has_many :klasses
  #accepts_nested_attributes_for :klasses

  #############
  # VARIABLES #
  #############
  enum status: [:pending, :active, :inactive, :deleted]

  ###############
  # VALIDATIONS #
  ###############
  validates_presence_of :name

  ###########
  # METHODS #
  ###########
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  before_action :registered?, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected
    def set_school
      p params
      @school = School.find(params[:id])
    end

    def registered?
      if !@school.registered?(current_user)
        flash[:alert] = "You are not enrolled in this school!"
        redirect_to :back
      end
    end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Principals:</strong>
  <ul>
    <%= @school.principals.each do |principal| %>
      <li><%= link_to principal.first_name, principal %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Teachers:</strong>
  <ul>
    <%= @school.teachers.each do |teachers| %>
    <li><%= link_to teachers.first_name, teachers %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Students:</strong>
  <ul>
    <%= @school.students.each do |students| %>
    <li><%= link_to students.first_name, students %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Classes:</strong>
  <ul>
    <%= @school.klasses.active.map(&:name).each do |klass| %>
    <li><%= link_to "#{klass}", klass_path(klass) %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong><%= link_to 'Add Class', new_klass_path(school: @school.id) %></strong>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>