config/routes.rb
Rails.application.routes.draw do
  devise_for :credentials
  #devise_for :users, controllers: { sessions: 'devise/sessions' }
  #devise_for :users, controllers: { sessions: "users/sessions" }
  resources :klasses
  resources :schools
  resources :users#, :only => [:show]
  resources :pages


  root 			to: 'pages#main'

  #match '/schools/add_klass/:id' => 'schools#add_klass', via: :get, as: :add_klass

  #resources :schools do
  #  post :add_klass, :on => :member
  #end

  #unauthenticated do
  #  root :to => 'sessions#new'
  #end

  #authenticated do
  #  root :to => 'pages#main'
  #end
  #get			  'sessions/new'

  #get	 'login'	=> 'sessions#new'
  #post	 'login'	=> 'sessions#create'
  #delete 'logout'	=> 'sessions#destroy'

  #devise_scope :user do
    #get   'login' =>  'devise/sessions#new'
    #get   'logout'=>  'devise/sessions#destroy'
  #  unauthenticated do
    #  root :to => 'sessions#new'
  #  end

    #authenticated do
    #  root :to => 'pages#main'
    #end
  #end
end

app/views/layouts/_banner.html.erb
<div class="banner">
  <h2> </h2>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Nemandi", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if credential_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_credential_session_path, method: "delete"%>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_credential_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nemandi</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/banner' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>