config/routes.rb
Rails.application.routes.draw do
  devise_for :credentials
  #devise_for :users, controllers: { sessions: 'devise/sessions' }
  #devise_for :users, controllers: { sessions: "users/sessions" }
  resources :klasses
  resources :schools
  resources :users#, :only => [:show]
  resources :pages


  root 			to: 'pages#main'

  #match '/schools/add_klass/:id' => 'schools#add_klass', via: :get, as: :add_klass

  #resources :schools do
  #  post :add_klass, :on => :member
  #end

  #unauthenticated do
  #  root :to => 'sessions#new'
  #end

  #authenticated do
  #  root :to => 'pages#main'
  #end
  #get			  'sessions/new'

  #get	 'login'	=> 'sessions#new'
  #post	 'login'	=> 'sessions#create'
  #delete 'logout'	=> 'sessions#destroy'

  #devise_scope :user do
    #get   'login' =>  'devise/sessions#new'
    #get   'logout'=>  'devise/sessions#destroy'
  #  unauthenticated do
    #  root :to => 'sessions#new'
  #  end

    #authenticated do
    #  root :to => 'pages#main'
    #end
  #end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  before_action :set_klass, only: [:show, :edit, :update, :destroy]
  before_action :authorized_to_view?, only: [:show, :edit, :update, :destroy]

  # GET /klasses
  # GET /klasses.json
  def index
    @klasses = Klass.all
  end

  # GET /klasses/1
  # GET /klasses/1.json
  def show
  end

  # GET /klasses/new
  def new
    @klass  = Klass.new
    @school = School.find(params[:school])
  end

  # GET /klasses/1/edit
  def edit
  end

  # POST /klasses
  # POST /klasses.json
  def create
    @klass = Klass.new(klass_params)
    @klass.active!
    @school = School.find(params[:klass][:school])
    @klass.school = @school
    @klass.register(:write, :teacher, current_user)
    respond_to do |format|
      if @klass.save
        format.html { redirect_to @klass, notice: 'Class was successfully created.' }
        format.json { render :show, status: :created, location: @klass }
      else
        format.html { render :new }
        format.json { render json: @klass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /klasses/1
  # PATCH/PUT /klasses/1.json
  def update
    respond_to do |format|
      if @klass.update(klass_params)
        format.html { redirect_to @klass, notice: 'Klass was successfully updated.' }
        format.json { render :show, status: :ok, location: @klass }
      else
        format.html { render :edit }
        format.json { render json: @klass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klasses/1
  # DELETE /klasses/1.json
  def destroy
    @klass.destroy
    respond_to do |format|
      format.html { redirect_to klasses_url, notice: 'Klass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected
    def set_klass
      @klass = Klass.find(params[:id])
    end

    def registered?
      if !@klass.registered?(current_user)
        flash[:alert] = "You are not registered for this class!"
        redirect_to :back
      end
    end

    def authorized_to_view?
      if !@klass.authorized_to_view?(current_user)
        flash[:alert] = "You are not registered for this class!"
        redirect_to :back
      end
    end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def klass_params
      params.require(:klass).permit(:name)
    end
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/views/klasses/_form.html.erb
<%= form_for(@klass) do |f| %>
  <% if @klass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@klass.errors.count, "error") %> prohibited this klass from being saved:</h2>

      <ul>
      <% @klass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.hidden_field :school, :value => @school.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/klasses/edit.html.erb
<h1>Editing Klass</h1>

<%= render 'form' %>

<%= link_to 'Show', @klass %> |
<%= link_to 'Back', klasses_path %>

app/views/klasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Klasses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @klasses.each do |klass| %>
      <tr>
        <td><%= klass.name %></td>
        <td><%= link_to 'Show', klass %></td>
        <td><%= link_to 'Edit', edit_klass_path(klass) %></td>
        <td><%= link_to 'Destroy', klass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Klass', new_klass_path %>

app/views/klasses/new.html.erb
<h1>New Klass</h1>

<%= render 'form' %>

<%= link_to 'Back', klasses_path %>

app/views/klasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @klass.name %>
</p>

<p>
  <strong>Teachers:</strong>
  <ul>
    <%= @klass.teachers.each do |teacher| %>
      <li><%= link_to teacher.first_name, teacher %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Students:</strong>
  <ul>
    <%= @klass.students.each do |student| %>
    <li><%= link_to student.first_name, student %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_klass_path(@klass) %> |
<%= link_to 'Back', klasses_path %>